### ISSUE TITLE
DB: Post table & Default script (tokens)

### ISSUE THREAD

**Issue by samanthahallcox** [AzzieDevelopment/tiger-talks#36]
- Find and replace 'TIgerSpaceId' with 'TigerSpaceId' in all scripts.
- Rerun Down, Up, and Default scripts

![image](https://user-images.githubusercontent.com/60751108/141530471-4929e7f7-1bab-4288-900e-4d26d914e422.png)

**Comment by AzzieDev** [comment]
Also in this issue: default.sql needs to include token values (doesn't really matter much but for consistency)

**Comment by samanthahallcox** [comment]
I fixed the casing issue in the post table, still need to add token default values. for now I'm using "no token"

**Comment by samanthahallcox** [comment]
@AzzieDev @zRyder see my previous comment on this issue

**Comment by AzzieDev** [comment]
@zRyder key issues to work on is the POST and COMMENT table timestamps being auto-generated on creation of new records, as well as a new column for each to be updated for bumps by backend.

Discord

**Comment by AzzieDev** [comment]
https://github.com/AzzieDevelopment/tiger-talks/tree/addEndpointsPost
