### ISSUE TITLE
Angular Material breaks things

### ISSUE THREAD

**Issue by samanthahallcox** [AzzieDevelopment/tiger-talks#37]
When trying to merge @pnguye18's pd/make-post branch into master, it broke the Sign-Up and Sign-In forms.

This gave no error messages on the client or server side, and the website did not crash. An important note is that the main difference between PD's make-post branch and my other FE branches is her use of Angular Material as a UI framework, So, I think we need to redesign the make-post component with Bootstrap styling and scrap any use of Angular Material.

**Comment by pnguye18** [comment]
make-post component was (hopefully) converted to Bootstrap. Hopefully this should fix things as when testing it locally on my local end, all the components seem to function as expected.
